services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./env/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    user: 1000:1000
    volumes:
      - ./:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_DATABASE: 'dev'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}
